"""Initial migration

Revision ID: 36c6abc73c23
Revises: 
Create Date: 2024-04-15 08:10:28.990502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c6abc73c23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(length=9),
               type_=sa.Enum('completed', 'ongoing', 'pending'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('completed', 'ongoing', 'pending'),
               type_=sa.TEXT(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###
