"""Added requirements table

Revision ID: 562a83c3042a
Revises: 694ae6e0aab9
Create Date: 2024-04-21 16:17:41.751425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562a83c3042a'
down_revision = '694ae6e0aab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(length=9),
               type_=sa.Enum('completed', 'ongoing', 'pending'),
               existing_nullable=True)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(length=256),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=256),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.TEXT(length=10),
               type_=sa.Enum('incomplete', 'evaluation', 'completed'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.Enum('incomplete', 'evaluation', 'completed'),
               type_=sa.TEXT(length=10),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(length=256),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(length=256),
               existing_nullable=True)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('completed', 'ongoing', 'pending'),
               type_=sa.TEXT(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###
