"""Change column names

Revision ID: 694ae6e0aab9
Revises: 36c6abc73c23
Create Date: 2024-04-15 08:59:53.152934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694ae6e0aab9'
down_revision = '36c6abc73c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_admin_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_admin_user_users'), 'users', ['user'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('student', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_enrollment_student_id_students', type_='foreignkey')
        batch_op.drop_constraint('fk_enrollment_instructor_instructors', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enrollment_instructor_instructors'), 'instructors', ['instructor'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_enrollment_student_students'), 'students', ['student'], ['id'])
        batch_op.drop_column('student_id')
        batch_op.drop_column('instructor_id')

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_instructors_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_instructors_user_users'), 'users', ['user'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_students_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_students_user_users'), 'users', ['user'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_students_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_students_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_instructors_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_instructors_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_enrollment_student_students'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_enrollment_instructor_instructors'), type_='foreignkey')
        batch_op.create_foreign_key('fk_enrollment_instructor_instructors', 'instructors', ['instructor_id'], ['id'])
        batch_op.create_foreign_key('fk_enrollment_student_id_students', 'students', ['student_id'], ['id'])
        batch_op.drop_column('student')
        batch_op.drop_column('instructor')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_admin_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_admin_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###
