"""added filename column to requirement files

Revision ID: e82991fa10b9
Revises: 8f27b1356b2b
Create Date: 2024-04-28 22:11:40.217090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82991fa10b9'
down_revision = '8f27b1356b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=64), nullable=True))

    with op.batch_alter_table('requirement_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_submissions', schema=None) as batch_op:
        batch_op.drop_column('filename')

    with op.batch_alter_table('requirement_materials', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
